---
title: "Visualizaciones - SINADEF"
Comment:
web: 
date:
output: 
  html_document:
    toc: true
    toc_float: true
    fig_width: 15
    fig_height: 10

---

```{r, error=F, warning=F,message=F}
library(scales)
library(dplyr)
library(lubridate)
library(tidyr)
library(gridExtra)
library(ggpubr)
library(tidyverse)
```


## Sexo
```{r, error=F, warning=F,message=F}
sinadef.sex <- readRDS("../../output/Long Formats/sinadef_longBySex_20200927.Rdata")

p.list <- lapply(sort(unique(sinadef.sex$sexo)), function(i) {
  sinadef.sex %>%
  filter(edad_cat.by5 != "Total" & sexo == i) %>%
  group_by(edad_cat.by5,sexo,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(month = format(as.Date(date, "%Y/%m/%d"), '%Y-%m'),
           edad_cat.by5, sexo)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(month) %>%
  ggplot(aes(factor(month), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01"))+
  scale_y_discrete(breaks = c("00-04","10-14","20-24","30-34","40-44","50-54","60-64","70-74","80-84","90-94"))  +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_wrap(vars(sexo))
})

do.call(grid.arrange, c(p.list, nrow=2,top="Monthly deaths in Perú from 2017 to 2020 by type of death"))
```

```{r, error=F, warning=F,message=F}
sinadef.sex %>%
  filter(edad_cat.by5 != "Total") %>%
  group_by(edad_cat.by5,sexo,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(week = format(as.Date(date, "%Y/%m/%d"), '%Y-%W'),
           edad_cat.by5, sexo)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(week) %>%
  ggplot(aes(factor(week), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "Weekly deaths in Perú from 2017 to 2020",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01")) +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_grid(rows = vars(sexo))
```

```{r}
rm(sinadef.sex)
```


## Nivel de instrucción
```{r, error=F, warning=F,message=F}
sinadef.nivins <- readRDS("../../output/Long Formats/sinadef_longByNivIns_20200927.Rdata")


p.list <- lapply(sort(unique(sinadef.nivins$niv.ins)), function(i) {
  sinadef.nivins %>%
  filter(edad_cat.by5 != "Total" & niv.ins == i) %>%
  group_by(edad_cat.by5,niv.ins,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(month = format(as.Date(date, "%Y/%m/%d"), '%Y-%m'),
           edad_cat.by5, niv.ins)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(month) %>%
  ggplot(aes(factor(month), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01"))+
  scale_y_discrete(breaks = c("00-04","10-14","20-24","30-34","40-44","50-54","60-64","70-74","80-84","90-94"))  +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_wrap(vars(niv.ins))
})

do.call(grid.arrange, c(p.list, nrow=2,top="Monthly deaths in Perú from 2017 to 2020 by type of death"))
```

```{r, error=F, warning=F,message=F}
sinadef.nivins %>%
  filter(edad_cat.by5 != "Total") %>%
  group_by(edad_cat.by5,niv.ins,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(week = format(as.Date(date, "%Y/%m/%d"), '%Y-%W'),
           edad_cat.by5, niv.ins)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(week) %>%
  ggplot(aes(factor(week), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "Weekly deaths in Perú from 2017 to 2020",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01")) +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_grid(rows = vars(niv.ins))
```

```{r}
rm(sinadef.nivins)
```


## Muertes Violentas
```{r, error=F, warning=F,message=F}
sinadef.muevio <- readRDS("../../output/Long Formats/sinadef_longByMueVio_20200927.Rdata")


p.list <- lapply(sort(unique(sinadef.muevio$mue.vio)), function(i) {
  sinadef.muevio %>%
  filter(edad_cat.by5 != "Total" & mue.vio == i) %>%
  group_by(edad_cat.by5,mue.vio,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(month = format(as.Date(date, "%Y/%m/%d"), '%Y-%m'),
           edad_cat.by5, mue.vio)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(month) %>%
  ggplot(aes(factor(month), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01"))+
  scale_y_discrete(breaks = c("00-04","10-14","20-24","30-34","40-44","50-54","60-64","70-74","80-84","90-94"))  +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_wrap(vars(mue.vio))
})

do.call(grid.arrange, c(p.list, nrow=2,top="Monthly deaths in Perú from 2017 to 2020 by type of death"))
```

```{r, error=F, warning=F,message=F}
sinadef.muevio %>%
  filter(edad_cat.by5 != "Total") %>%
  group_by(edad_cat.by5,mue.vio,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(week = format(as.Date(date, "%Y/%m/%d"), '%Y-%W'),
           edad_cat.by5, mue.vio)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(week) %>%
  ggplot(aes(factor(week), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "Weekly deaths in Perú from 2017 to 2020",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01")) +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_grid(rows = vars(mue.vio))
```

```{r}
rm(sinadef.muevio)
```


## Old versions



```{r eval = FALSE, echo = FALSE}
sinadef.sex <- readRDS("../../output/Long Formats/sinadef_longBySex_20200927.Rdata")

sinadef.sex %>%
  filter(edad_cat.by5 != "Total") %>%
  group_by(edad_cat.by5,sexo,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(week = format(as.Date(date, "%Y/%m/%d"), '%Y-%W'),
           edad_cat.by5, sexo)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(week) %>%
  ggplot(aes(factor(week), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "Weekly deaths in Perú from 2017 to 2020",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01")) +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")+
  facet_grid(rows = vars(sexo))
```

```{r eval = FALSE, echo = FALSE}
sinadef.sex %>%
  filter(edad_cat.by5 != "Total") %>%
  group_by(edad_cat.by5,sexo,date) %>%
  summarize(n=sum(n))%>% 
  ungroup() %>% 
  group_by(week = format(as.Date(date, "%Y/%m/%d"), '%Y-%W'),
           edad_cat.by5)%>% 
  summarise(n=sum(n),
            date=min(as.Date(date, "%Y/%m/%d"))
  ) %>% ungroup() %>%
  arrange(week) %>%
  ggplot(aes(factor(week), edad_cat.by5)
         ) + 
  geom_tile(aes(fill = n),colour = "white", na.rm = TRUE) +
  scale_fill_continuous(low = "white", high = "red") +  
  guides(fill= guide_colourbar(title="Total Deaths"))+
  theme_bw() + theme_minimal() + 
  labs(title = "Weekly deaths in Perú from 2017 to 2020",
       x = "Year", y = "Age category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(breaks = c("2017-01","2018-01","2019-01","2020-01")) +
  geom_vline(xintercept = c("2017-01","2018-01","2019-01","2020-01"),
             linetype = "twodash")
```

