---
title: "Transformación de datos"
output: html_document
---

```{r}
options(dplyr.summarise.inform=F) 
library(tidyverse)
library(lubridate)
source('../_funciones/func_extract_SINADEF.R', echo = TRUE, encoding="UTF-8")
#sinadef <- read_csv("../../sinadef_20200927.csv")
sinadef <- readRDS("../../output/sinadef_2020-11-26.Rdata")
```




```{r}
sinadef.long <- sinadef %>% dplyr::mutate(mue.vio = replace(mue.vio,
                                                            mue.vio!="NO REGISTRO/NA",
                                                            "MUERTE VIOLENTA"))
  
sinadef2 <- sinadef.long %>% mutate(var_total = paste0(sexo,".",niv.ins,".",mue.vio) )

sinadef2.todos <- sinadef2 %>%
   dplyr::mutate(annus2 = annus) %>%
   dplyr::filter(annus2 ==2017) %>%
   dplyr::group_by(annus2) %>%
  nest() %>%
   dplyr::mutate(extract_SINADEF = map(.x=data, 
                               .f=~extract_SINADEF(.x,"var_total")))


saveRDS(sinadef2.todos,"../../output/Long Formats/sinadef_long_v2_2017.Rdata")

sinadef2.todos <- sinadef2 %>%
  mutate(annus2 = annus) %>%
    filter(annus2 ==2018) %>%
  group_by(annus2) %>%
  nest() %>%
  mutate(extract_SINADEF = map(.x=data, 
                               .f=~extract_SINADEF(.x,"var_total")))


saveRDS(sinadef2.todos,"../../output/Long Formats/sinadef_long_v2_2018.Rdata")

sinadef2.todos <- sinadef2 %>%
  mutate(annus2 = annus) %>%
    filter(annus2 ==2019) %>%
  group_by(annus2) %>%
  nest() %>%
  mutate(extract_SINADEF = map(.x=data, 
                               .f=~extract_SINADEF(.x,"var_total")))


saveRDS(sinadef2.todos,"../../output/Long Formats/sinadef_long_v2_2019.Rdata")

sinadef2.todos <- sinadef2 %>%
  mutate(annus2 = annus) %>%
    filter(annus2 ==2020) %>%
  group_by(annus2) %>%
  nest() %>%
  mutate(extract_SINADEF = map(.x=data, 
                               .f=~extract_SINADEF(.x,"var_total")))


saveRDS(sinadef2.todos,"../../output/Long Formats/sinadef_long_v2_2020.Rdata")
```

```{r}
sinadef_sexo <- extract_SINADEF(sinadef,"sexo")
saveRDS(sinadef_sexo,file.path(paste0("../../output/Long Formats/sinadef_longBySex_",max(sinadef$fecha),".Rdata")))
rm(sinadef_sexo)
gc()
```

```{r}
sinadef_niv.ins <- extract_SINADEF(sinadef,"niv.ins")
saveRDS(sinadef_niv.ins,file.path(paste0("../../output/Long Formats/sinadef_longByNivIns_",max(sinadef$fecha),".Rdata")))
rm(sinadef_niv.ins)
gc()
```

```{r}
sinadef_mue.vio <- extract_SINADEF(sinadef,"mue.vio")
saveRDS(sinadef_mue.vio,file.path(paste0("../../output/Long Formats/sinadef_longByMueVio_",max(sinadef$fecha),".Rdata")))
rm(sinadef_mue.vio)
gc()
```

```{r}
sinadef_tipo.seg <- extract_SINADEF(sinadef,"tipo.seg")
saveRDS(sinadef_tipo.seg,file.path(paste0("../../output/Long Formats/sinadef_longByTipoSeg_",max(sinadef$fecha),".Rdata")))
rm(sinadef_tipo.seg)
gc()
```

```{r}
sinadef_CIE10.cat <- extract_SINADEF(sinadef,"CIE10.cat")
saveRDS(sinadef_CIE10.cat,file.path(paste0("../../output/Long Formats/sinadef_longByCIE10cat_",max(sinadef$fecha),".Rdata")))
rm(sinadef_CIE10.cat)
gc()
```

## Long by years



```{r}
# 2017

df <- readRDS("../../output/Long Formats/sinadef_long_v2_2017.Rdata") %>% 
  .[1,3] %>% 
  pull(.) %>%
  .[[1]] 


df %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]") %>%
  saveRDS(file.path(paste0("../../output/Long Formats/2017_long_",max(sinadef$fecha),".Rdata")))


# 2018

df <- readRDS("../../output/Long Formats/sinadef_long_v2_2018.Rdata")  %>% 
  .[1,3] %>% 
  pull(.) %>%
  .[[1]] 

df %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]") %>%
  saveRDS(file.path(paste0("../../output/Long Formats/2018_long_",max(sinadef$fecha),".Rdata")))


# 2019

df <- readRDS("../../output/Long Formats/sinadef_long_v2_2019.Rdata") %>% 
  .[1,3] %>% 
  pull(.) %>%
  .[[1]] 

df %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]") %>%
  saveRDS(file.path(paste0("../../output/Long Formats/2019_long_",max(sinadef$fecha),".Rdata")))

# 2020

df <- readRDS("../../output/Long Formats/sinadef_long_v2_2020.Rdata") %>% 
  .[1,3] %>% 
  pull(.) %>%
  .[[1]] 

df %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]") %>%
  saveRDS(file.path(paste0("../../output/Long Formats/2020_long_",max(sinadef$fecha),".Rdata")))
```



```{r}
sinadef <- readRDS("../../output/Long Formats/sinadef_long_v2_2017.Rdata")

df_2017 <- sinadef$extract_SINADEF[[1]] %>% 
  group_by(dep,prov,distr,edad_cat.by5,var_total,week) %>% 
  summarise(N = sum(n)) %>% 
  filter(edad_cat.by5!="Total")  %>% 
  ungroup() %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]")


saveRDS(df_2017,file.path(paste0("../../output/Long Formats/2017_long",".Rdata")))
```

```{r}
sinadef <- readRDS("../../output/Long Formats/sinadef_long_v2_2018.Rdata")

df_2018 <- sinadef$extract_SINADEF[[1]] %>% group_by(dep,prov,distr,edad_cat.by5,var_total,week) %>% summarise(N = sum(n)) %>% filter(edad_cat.by5!="Total")  %>% 
  ungroup() %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]")
saveRDS(df_2018,file.path(paste0("../../output/Long Formats/2018_long",".Rdata")))
```

```{r}
sinadef <- readRDS("../../output/Long Formats/sinadef_long_v2_2019.Rdata")

df_2019 <- sinadef$extract_SINADEF[[1]] %>% group_by(dep,prov,distr,edad_cat.by5,var_total,week) %>% summarise(N = sum(n)) %>% filter(edad_cat.by5!="Total")  %>% 
  ungroup() %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]")
saveRDS(df_2019,file.path(paste0("../../output/Long Formats/2019_long",".Rdata")))
```

```{r}
sinadef <- readRDS("../../output/Long Formats/sinadef_long_v2_2020.Rdata")

df_2020 <- sinadef$extract_SINADEF[[1]] %>% group_by(dep,prov,distr,edad_cat.by5,var_total,week) %>% summarise(N = sum(n)) %>% filter(edad_cat.by5!="Total")  %>% 
  ungroup() %>%
  separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]")
saveRDS(df_2020,file.path(paste0("../../output/Long Formats/2020_long",".Rdata")))
```






```{r}
# b <- a %>% 
#   ungroup() %>%
#   separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]") %>%
#   mutate(Accidente = replace(Accidente, Accidente =="ACCIDENTE DE TRABAJO" |
#                                 Accidente =="HOMICIDIO"|
#                                 Accidente =="OTROS"|
#                                 Accidente =="ACCIDENTE DE TRANSITO"|
#                                 Accidente =="SUICIDIO",
#                              "MUERTE VIOLENTA"
#                              )) %>%
#   group_by(dep,prov,distr,edad_cat.by5,Sexo,Educacion,Accidente,week)%>% 
#   summarise(N = sum(N))
# 
# b <- head(a,10)
# 
# b
# 
# b %>% 
#   ungroup() %>%
#   separate(col=c("var_total"), into=c("Sexo","Educacion","Accidente"),sep="[.]")

```

